version: '3'
services:

  postgres:
    image: postgres:16.3
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - emoti-rise

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - emoti-rise

  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    networks:
      - emoti-rise

volumes:
  postgres:
    driver: local

networks:
  emoti-rise:
    driver: bridge
